# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Hardhat CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn
    - name: Compile Smart Contract
      run: npx hardhat compile
    - name: Unit testcases 
      run: npx hardhat test
    - name: smart-contract coverage 
      run: npx hardhat coverage
    - name: linting
      run: npx prettier  --write 'contracts/**/*.sol' 
    - name: Install pip
      run: python -m pip install --upgrade pip
    - name: Install slither & solc
      run: pip3 install slither-analyzer solc-select
    - name: Install solidty and use 0.7.6
      run:  solc-select install 0.7.6 && solc-select use 0.7.6
    - name: Generate audit report
      run: slither .

    
      
 
    
